package caches

var MAX_CACHE_SIZE = 1024
var USE_CACHE = true
var CACHE_DEFAULT_CONNECTIONS = 1000
var CACHE_MAX_IDLE_CONNECTIONS = 80
var CACHE_MAX_CONNECTIONS = 1000
var CACHE_PARALLEL_PROCESS = 1000
